# Generated by Django 4.1.1 on 2022-10-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vaga_alter_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formação',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instituicao', models.CharField(max_length=100)),
                ('formacao', models.CharField(max_length=100)),
                ('trabalho', models.CharField(max_length=100)),
            ],
        ),
    ]
