# Generated by Django 4.1.1 on 2022-10-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_formação'),
    ]

    operations = [
        migrations.AddField(
            model_name='formação',
            name='datinic_for',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formação',
            name='dattermi_for',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formação',
            name='descricao_formacao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
