# Generated by Django 4.1.1 on 2022-10-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profissional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='cnpj',
            field=models.CharField(max_length=100),
        ),
    ]
