# Generated by Django 4.1.1 on 2022-10-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profissional_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='cnpj',
            field=models.CharField(max_length=20),
        ),
    ]
