# Generated by Django 4.1.1 on 2022-10-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_profissional_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscrição',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.CharField(max_length=100)),
            ],
        ),
    ]
