# Generated by Django 4.1.1 on 2022-10-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_inscrição'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscrição',
            old_name='tempo',
            new_name='descricao',
        ),
        migrations.AlterField(
            model_name='profissional',
            name='cnpj',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='linkedin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='twitter',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
