# Generated by Django 4.1.1 on 2022-10-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_tempo_inscrição_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
