# Generated by Django 4.1.1 on 2022-10-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_usuario_cidade"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expreriencias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao_experiencia", models.CharField(max_length=32)),
            ],
        ),
    ]
