# Generated by Django 4.1.1 on 2022-10-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_rename_cnpj_profissional_cpf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profissional",
            old_name="cpf",
            new_name="CPF",
        ),
    ]
