# Generated by Django 4.1.1 on 2022-10-27 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_rename_cpf_profissional_cpf"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscrição",
            name="vaga",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.vaga",
            ),
            preserve_default=False,
        ),
    ]
